### ISSUE TITLE
Compatibility issue with firebase_messaging plugin on Android 10

### ISSUE THREAD

**Issue by svendroid** [MaikuB/flutter_appauth#104]
On a Pixel 3 with Android 10 my app crashes with following exception when it is restarted and the user has already been logged in.

```
2020-04-21 08:57:25.038 17737-17737/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: -, PID: 17737
    java.lang.NullPointerException: Attempt to read from field 'io.flutter.plugin.common.MethodChannel$Result io.crossingthestreams.flutterappauth.FlutterAppauthPlugin$PendingOperation.result' on a null object reference
        at io.crossingthestreams.flutterappauth.FlutterAppauthPlugin.finishWithSuccess(FlutterAppauthPlugin.java:347)
        at io.crossingthestreams.flutterappauth.FlutterAppauthPlugin.access$600(FlutterAppauthPlugin.java:39)
        at io.crossingthestreams.flutterappauth.FlutterAppauthPlugin$4.onTokenRequestCompleted(FlutterAppauthPlugin.java:325)
        at net.openid.appauth.AuthorizationService$TokenRequestTask.onPostExecute(AuthorizationService.java:508)
        at net.openid.appauth.AuthorizationService$TokenRequestTask.onPostExecute(AuthorizationService.java:395)
        at android.os.AsyncTask.finish(AsyncTask.java:755)
        at android.os.AsyncTask.access$900(AsyncTask.java:192)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

On a Nexus 5X Android 8.1.0 it does not crash.
On a Pixel XL Android 10 it does not crash.

It crashes since I added firebase_messaging (https://pub.dev/packages/firebase_messaging) to the project.
Error only occurs when app is terminated and then restarted. The initial Login works.

Did someone experienced similiar issues when combining the plugin with firebase_messaging?

---
Environment:
Flutter (Channel stable, v1.12.13+hotfix.9)
flutter_appauth: ^0.8.2
firebase_messaging: ^6.0.13

**Comment by svendroid** [comment]
The error was inside my app code. It had nothing to do with Android 10 or flutter_messaging.
The cause for the problem was that `FlutterAppAuth#token` method would be called several times in some edge case (maybe cause by the additional plugin). This led to PlatformExceptions in https://github.com/MaikuB/flutter_appauth/blob/ccf55820499983976e11a870e478f3c9f9a5d5d7/flutter_appauth/android/src/main/java/io/crossingthestreams/flutterappauth/FlutterAppauthPlugin.java#L113 which I interpreted as a failed authentication and therefore called logout in my app. I guess the result of several PendingOperations leads to the NullPointerException because it is cleared after the first operation returns.

Is there a reason why there only can be one PendingOperation? Or maybe I could improve the documentation on this behaviour.

**Comment by MaikuB** [comment]
It's primarily to ensure a single operation is taking place, particularly around sign-in (e.g. imagine multiple browser instances/tabs being open on older devices, each of which then redirect back after signing in). The google_sign_in plugin has the same protection mechanisms as well that I based this off
