### ISSUE TITLE
 Android app crash when use flutter_appauth connect local IdentityServer4 came across http 

### ISSUE THREAD

**Issue by huantd0111** [MaikuB/flutter_appauth#131]
I am getting this error if I am trying to use http. My app on IOS run well but android not word. I try to change https link and it work well. However our test environment uses http link. Is there any way to use http instead of https?

 java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:355)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:246)
        at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:784)
     Caused by: java.lang.IllegalArgumentException: only https connections are permitted
        at net.openid.appauth.Preconditions.checkArgument(Preconditions.java:116)
        at net.openid.appauth.connectivity.DefaultConnectionBuilder.openConnection(DefaultConnectionBuilder.java:51)
        at net.openid.appauth.AuthorizationServiceConfiguration$ConfigurationRetrievalAsyncTask.doInBackground(AuthorizationServiceConfiguration.java:327)
        at net.openid.appauth.AuthorizationServiceConfiguration$ConfigurationRetrievalAsyncTask.doInBackground(AuthorizationServiceConfiguration.java:305)
        at android.os.AsyncTask$2.call(AsyncTask.java:334)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:246) 
        at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:784) 

I've tried add **_allowInsecureConnections_** to **true**, and add attribute **android:usesCleartextTraffic="true"** to node application in **AndroidManifest.xml** but it does not work. The application runs fine when I use the **https** link. 

Version
flutter_appauth: 0.9.2

```
final AuthorizationResponse result = await _appAuth.authorize(
        AuthorizationRequest(_clientId, _redirectUrl,
          promptValues: ['login'],
            allowInsecureConnections: true,
          discoveryUrl: _discoveryUrl, scopes: _scopes, loginHint: 'bob'),
      );


```
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="net.jaggerwang.fip">

    <application
            android:name="io.flutter.app.FlutterApplication"
            android:label="Base wallet"
            android:icon="@mipmap/ic_launcher"
            android:usesCleartextTraffic="true">
        ...
    </application>
</manifest>
```

**Comment by xiongtec** [comment]
In the java app auth there is a callback in lower http client to bypass this for testing.

**Comment by huantd0111** [comment]
> In the java app auth there is a callback in lower http client to bypass this for testing.

Can you give some flutter example code on that. thank you!

**Comment by xuhongxu96** [comment]
When `serviceConfigurationParameters` is null, `AuthorizationServiceConfiguration.fetchFromUrl` will be called, but the `insecureConnectionBuilder` is not used here.

For now, `insecureConnectionBuilder` is only used for `performAuthorization`.

So, in your case, `discoveryUrl` is used without `serviceConfigurationParameters` and the app will crash.

**Comment by MaikuB** [comment]
@huantd0111 I merged the PR that @xuhongxu96 submitted so believe the issue should be fixed now in the 0.9.2+4 release. I don't have a http server of mine to confirm though as the http support was a community contribution so I'm relying on the help of the community for it. Previously I ran a local http proxy but even that might not be a good enough test. Let me know how you go

**Comment by brickolicious** [comment]
Where it would crash before (using a local oidc idsrv4 and 10.0.2.2 in the emulator) i now just get a network error. 
If the goal was to prevent the crashing its a success, just not sure if the network error is directly related to the insecure connection or just my own issue.

code: token_failed
message:  Failed to get token: [error: null, description: Network error]

**Comment by WalacyRodrigues** [comment]
> @huantd0111 I merged the PR that @xuhongxu96 submitted so believe the issue should be fixed now in the 0.9.2+4 release. I don't have a http server of mine to confirm though as the http support was a community contribution so I'm relying on the help of the community for it. Previously I ran a local http proxy but even that might not be a good enough test. Let me know how you go

Hello!
I tested it and it didn't work...

**Comment by xuhongxu96** [comment]
> 
> 
> > @huantd0111 I merged the PR that @xuhongxu96 submitted so believe the issue should be fixed now in the 0.9.2+4 release. I don't have a http server of mine to confirm though as the http support was a community contribution so I'm relying on the help of the community for it. Previously I ran a local http proxy but even that might not be a good enough test. Let me know how you go
> 
> Hello!
> I tested it and it didn't work...

Do you use issuer or discoveryUrl config?

My PR https://github.com/MaikuB/flutter_appauth/pull/139 only fixed http discoveryUrl. 
If you use http issuer, we must wait for https://github.com/openid/AppAuth-Android/pull/594

**Comment by bryanCancelWT** [comment]
@huantd0111 why is your autofill hint bob?

is it the actual email of the user, or the actual user name?

or is it perhaps the the input TYPE from html?
or perhaps the input AUTOCOMPLETE value from html?
