### ISSUE TITLE
Android appAuth: ActivityNotFound exception crash when browser is disabled/missing from user device.

### ISSUE THREAD

**Issue by urbanjagodic** [MaikuB/flutter_appauth#168]
AppAuth issue: https://github.com/openid/AppAuth-Android/issues/459

When user tries to log in using **flutter_appauth plugin** and doesn't have a browser on his device or its disabled,
the application crashes with the following error:

```java
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: PID: 5758
    android.content.ActivityNotFoundException
        at net.openid.appauth.AuthorizationService.prepareAuthorizationRequestIntent(AuthorizationService.java:372)
        at net.openid.appauth.AuthorizationService.getAuthorizationRequestIntent(AuthorizationService.java:267)
        at net.openid.appauth.AuthorizationService.getAuthorizationRequestIntent(AuthorizationService.java:296)
        at io.crossingthestreams.flutterappauth.FlutterAppauthPlugin.performAuthorization(FlutterAppauthPlugin.java:314)
        at io.crossingthestreams.flutterappauth.FlutterAppauthPlugin.access$300(FlutterAppauthPlugin.java:42)
        at io.crossingthestreams.flutterappauth.FlutterAppauthPlugin$2.onFetchConfigurationCompleted(FlutterAppauthPlugin.java:234)
        at net.openid.appauth.AuthorizationServiceConfiguration$ConfigurationRetrievalAsyncTask.onPostExecute(AuthorizationServiceConfiguration.java:364)
        at net.openid.appauth.AuthorizationServiceConfiguration$ConfigurationRetrievalAsyncTask.onPostExecute(AuthorizationServiceConfiguration.java:305)
        at android.os.AsyncTask.finish(AsyncTask.java:755)
        at android.os.AsyncTask.access$900(AsyncTask.java:192)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

Would be possible to catch the exception and instead, open up a dialog pop-up which informs the 
user to enable/install a browser to continue with login.

_Issue reproduced on Pixel XL API 29 emulator with disabled Chrome browser._

**Comment by sarbogast** [comment]
On my simulator, I get this exception as soon as I initiate the authentication process, and even if I configured Chrome as the browser. I don't get it.

**Comment by MaikuB** [comment]
@urbanjagodic This looks like an issue with the native AppAuth Android SDK so not much I can do about it. There's already try/catch statements in the plugin (https://github.com/MaikuB/flutter_appauth/blob/8d266d819ec1fe15fdc7a8bf17d03cbb4655a975/flutter_appauth/android/src/main/java/io/crossingthestreams/flutterappauth/FlutterAppauthPlugin.java#L161)  and the exception is flowing through to be caught and it's likely due to the issue you mentioned. Even if it were possible, it's up to the application to show the dialog as plugin shouldn't make assumptions on what text should be displayed in an application and plugins don't get access to the `BuildContext`.

In light of this, I'll be closing this issue as it's a problem to do with the native SDK and there isn't anything that can be done here

**Comment by matecode** [comment]
Hi. I want to reopen this issue because I think there could be a mistake in error handling.

If I use the lib with discovering the service endpoint via discovery url, then you first fetch all needed information and then call performAuthorization. In this case, you are still in the postExcecute of an AsyncTask and therefore it seems that you cannot catch the ActivityNotFoundException. 

Im still not sure how to work around these AsyncTask Exception hell, but if you also catch the Exception in performAuthorization method, the error is catched

```
        try {
            AuthorizationService authorizationService = allowInsecureConnections ? insecureAuthorizationService : defaultAuthorizationService;
            Intent authIntent = authorizationService.getAuthorizationRequestIntent(authRequestBuilder.build());
            mainActivity.startActivityForResult(authIntent, exchangeCode ? RC_AUTH_EXCHANGE_CODE : RC_AUTH);
        } catch (Exception ex) {
            finishWithError(AUTHORIZE_AND_EXCHANGE_CODE_ERROR_CODE,ex.getMessage());
        }
```

**Comment by matecode** [comment]
Hi. I want to ask you @MaikuB to reopen this issue because I think there could be a mistake in error handling.

If I use the lib with discovering the service endpoint via discovery url, then you first fetch all needed information and then call performAuthorization. In this case, you are still in the postExcecute of an AsyncTask and therefore it seems that you cannot catch the ActivityNotFoundException. 

Im still not sure how to work around these AsyncTask Exception hell, but if you also catch the Exception in performAuthorization

```
        try {
            AuthorizationService authorizationService = allowInsecureConnections ? insecureAuthorizationService : defaultAuthorizationService;
            Intent authIntent = authorizationService.getAuthorizationRequestIntent(authRequestBuilder.build());
            mainActivity.startActivityForResult(authIntent, exchangeCode ? RC_AUTH_EXCHANGE_CODE : RC_AUTH);
        } catch (Exception ex) {
            finishWithError(AUTHORIZE_AND_EXCHANGE_CODE_ERROR_CODE,ex.getMessage());
        }
```
