### ISSUE TITLE
Trust anchor for certification path not found

### ISSUE THREAD

**Issue by karezza** [MaikuB/flutter_appauth#173]
Using Samsung S20 w/ Android.

I've installed the needed CA from my local lan on my mobile device.  From the mobile I can browse to https://server/adfs/.well-known/openid-configuration and get the discovery JSON & it shows as secured, clicking on the certificate shows the certificate as valid.

Yet, when using flutter_appauth I'm seeing "Trust anchor for certification path not found".

Note, I can make this work by using AuthorizationServiceConfiguration instead and specifying values I obtained by manually going to the discover uri.

```
I/System.out(13802): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(13802): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(13802): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(13802): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(13802): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(13802): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(13802): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(13802): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(13802): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(13802): (HTTPLog)-Static: isSBSettingEnabled false
E/AppAuth (13802): Network error when retrieving discovery document
E/AppAuth (13802): javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
E/AppAuth (13802): 	at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:362)
E/AppAuth (13802): 	at com.android.org.conscrypt.ConscryptEngine.convertException(ConscryptEngine.java:1134)
E/AppAuth (13802): 	at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1089)
E/AppAuth (13802): 	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:876)
E/AppAuth (13802): 	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:747)
E/AppAuth (13802): 	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:712)
E/AppAuth (13802): 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:849)
E/AppAuth (13802): 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.access$100(ConscryptEngineSocket.java:722)
E/AppAuth (13802): 	at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:238)
E/AppAuth (13802): 	at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:217)
E/AppAuth (13802): 	at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:1450)
E/AppAuth (13802): 	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:1399)
E/AppAuth (13802): 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:1343)
E/AppAuth (13802): 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:221)
E/AppAuth (13802): 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:144)
E/AppAuth (13802): 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:106)
E/AppAuth (13802): 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:400)
E/AppAuth (13802): 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:333)
E/AppAuth (13802): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
E/AppAuth (13802): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
E/AppAuth (13802): 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)
E/AppAuth (13802): 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)
E/AppAuth (13802): 	at net.openid.appauth.AuthorizationServiceConfiguration$ConfigurationRetrievalAsyncTask.doInBackground(AuthorizationServiceConfiguration.java:330)
E/AppAuth (13802): 	at net.openid.appauth.AuthorizationServiceConfiguration$ConfigurationRetrievalAsyncTask.doInBackground(AuthorizationServiceConfiguration.java:305)
E/AppAuth (13802): 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
E/AppAuth (13802): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AppAuth (13802): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
E/AppAuth (13802): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AppAuth (13802): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AppAuth (13802): 	at java.lang.Thread.run(Thread.java:923)
E/AppAuth (13802): Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
E/AppAuth (13802): 	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:661)
E/AppAuth (13802): 	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:510)
E/AppAuth (13802): 	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:428)
E/AppAuth (13802): 	at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:356)
E/AppAuth (13802): 	at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
E/AppAuth (13802): 	at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:90)
E/AppAuth (13802): 	at com.android.org.conscrypt.ConscryptEngineSocket$2.checkServerTrusted(ConscryptEngineSocket.java:161)
E/AppAuth (13802): 	at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:250)
E/AppAuth (13802): 	at com.android.org.conscrypt.ConscryptEngine.verifyCertificateChain(ConscryptEngine.java:1644)
E/AppAuth (13802): 	at com.android.org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
E/AppAuth (13802): 	at com.android.org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:568)
E/AppAuth (13802): 	at com.android.org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1095)
E/AppAuth (13802): 	at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1079)
E/AppAuth (13802): 	... 27 more
E/AppAuth (13802): Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
E/AppAuth (13802): 	... 40 more
I/flutter (13802): login failed, exeception caught: PlatformException(discovery_failed, Error retrieving discovery document: [error: null, description: Network error], null, null)
```

**Comment by karezza** [comment]
Note the following method used to allow self-signed certificates in general, does not appear to help. 

```
class MyHttpOverrides extends HttpOverrides{
  @override
  HttpClient createHttpClient(SecurityContext context){
    return super.createHttpClient(context)
      ..badCertificateCallback = (X509Certificate cert, String host, int port)=> true;
  }
}

void main() {
    HttpOverrides.global = new MyHttpOverrides();
```

**Comment by karezza** [comment]
Solution here:  https://github.com/MaikuB/flutter_appauth/issues/176
