### ISSUE TITLE
Execution failed for task ':app:processDebugResources'.

### ISSUE THREAD

**Issue by intako** [MaikuB/flutter_appauth#2]
Hello, I installed the package (0.0.4), added _build.gradle_, like was said in the _Android setup_ section :
```
        manifestPlaceholders = [
                'appAuthRedirectScheme': 'test.driver'
        ]
```

And also redirect activity to the _AndroidManifest.xml_:
```
<activity android:name="net.openid.appauth.RedirectUriReceiverActivity">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data android:scheme="test.driver" />
            </intent-filter>
        </activity>
```

The error occurs right after plugin installation, even without lib imported:
```
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  Output:  D:\projects\Flutter\gp\driver\build\app\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:190: error: resource android:attr/fontVariationSettings not found.
  D:\projects\Flutter\gp\driver\build\app\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:191: error: resource android:attr/ttcIndex not found.
  error: failed linking references.

  Command: C:\Users\Zver\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\6595a8e560e34ac981e3c20f4ba88937\aapt2-3.2.1-4818971-windows\aapt2.exe link -I\
          C:\Users\Zver\AppData\Local\Android\sdk\platforms\android-27\android.jar\
          --manifest\
          D:\projects\Flutter\gp\driver\build\app\intermediates\merged_manifests\debug\processDebugManifest\merged\AndroidManifest.xml\
          -o\
          D:\projects\Flutter\gp\driver\build\app\intermediates\processed_res\debug\processDebugResources\out\resources-debug.ap_\
          -R\
          @D:\projects\Flutter\gp\driver\build\app\intermediates\incremental\processDebugResources\resources-list-for-resources-debug.ap_.txt\
          --auto-add-overlay\
          --java\
          D:\projects\Flutter\gp\driver\build\app\generated\not_namespaced_r_class_sources\debug\processDebugResources\r\
          --custom-package\
          net.getpacked.driver\
          -0\
          apk\
          --output-text-symbols\
          D:\projects\Flutter\gp\driver\build\app\intermediates\symbols\debug\R.txt\
          --no-version-vectors
  Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0
  Output:  C:\Users\Zver\.gradle\caches\transforms-1\files-1.1\core-1.0.0-rc01.aar\725f987e2342d4e84333cf9b5173909c\res\values\values.xml:89:5-125:25: AAPT: error: resource android:attr/fontVariationSettings not found.

  C:\Users\Zver\.gradle\caches\transforms-1\files-1.1\core-1.0.0-rc01.aar\725f987e2342d4e84333cf9b5173909c\res\values\values.xml:89:5-125:25: AAPT: error: resource android:attr/ttcIndex not found.

  error: failed linking references.
  Command: C:\Users\Zver\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\6595a8e560e34ac981e3c20f4ba88937\aapt2-3.2.1-4818971-windows\aapt2.exe link -I\
          C:\Users\Zver\AppData\Local\Android\sdk\platforms\android-27\android.jar\
          --manifest\
          D:\projects\Flutter\gp\driver\build\app\intermediates\merged_manifests\debug\processDebugManifest\merged\AndroidManifest.xml\
          -o\
          D:\projects\Flutter\gp\driver\build\app\intermediates\processed_res\debug\processDebugResources\out\resources-debug.ap_\
          -R\
          @D:\projects\Flutter\gp\driver\build\app\intermediates\incremental\processDebugResources\resources-list-for-resources-debug.ap_.txt\
          --auto-add-overlay\
          --java\
          D:\projects\Flutter\gp\driver\build\app\generated\not_namespaced_r_class_sources\debug\processDebugResources\r\
          --custom-package\
          net.getpacked.driver\
          -0\
          apk\
          --output-text-symbols\
          D:\projects\Flutter\gp\driver\build\app\intermediates\symbols\debug\R.txt\
          --no-version-vectors
  Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
Finished with error: Gradle task assembleDebug failed with exit code 1
```

Could you suggest how I can solve this problem?
Thanks in advance.

**Comment by MaikuB** [comment]
As this library uses AndroidX, you need to ensure your app has been migrated to AndroidX

https://developer.android.com/jetpack/androidx/migrate

**Comment by intako** [comment]
Thanks, Michael, it helped.
But now I've got another problem, after calling _appAuth.authorizeAndExchangeCode_ with valid _discoveryUrl_, _client_id_ and _redirect_uri_ I get this:
```
I/Choreographer(14230): Skipped 39 frames!  The application may be doing too much work on its main thread.
D/NetworkSecurityConfig(14230): No Network Security Config specified, using platform default
D/EGL_emulation(14230): eglMakeCurrent: 0xe2b05660: ver 2 0 (tinfo 0xe2b03e70)
I/OpenGLRenderer(14230): Davey! duration=784ms; Flags=1, IntendedVsync=97567514267827, Vsync=97568164267801, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=97568167344090, AnimationStart=97568167405530, PerformTraversalsStart=97568167644640, DrawStart=97568176679910, SyncQueued=97568178288610, SyncStart=97568195443690, IssueDrawCommandsStart=97568196242160, SwapBuffers=97568255829510, FrameCompleted=97568315719470, DequeueBufferDuration=17335000, QueueBufferDuration=380000, 
D/        (14230): HostConnection::get() New Host Connection established 0xd047fe00, tid 14253
D/EGL_emulation(14230): eglMakeCurrent: 0xe885b920: ver 2 0 (tinfo 0xdfe85250)
I/net.auth.auth(14230): Rejecting re-init on previously-failed class java.lang.Class<net.openid.appauth.browser.CustomTabManager$1>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/customtabs/CustomTabsServiceConnection;
I/net.auth.auth(14230):   at void net.openid.appauth.AuthorizationService.<init>(android.content.Context, net.openid.appauth.AppAuthConfiguration) (AuthorizationService.java:96)
I/net.auth.auth(14230):   at void net.openid.appauth.AuthorizationService.<init>(android.content.Context) (AuthorizationService.java:83)
I/net.auth.auth(14230):   at void io.crossingthestreams.flutterappauth.FlutterAppauthPlugin.performAuthorization(net.openid.appauth.AuthorizationServiceConfiguration, java.lang.String, java.lang.String, java.util.ArrayList, java.lang.String, java.util.Map, boolean) (FlutterAppauthPlugin.java:221)
I/net.auth.auth(14230):   at void io.crossingthestreams.flutterappauth.FlutterAppauthPlugin.access$200(io.crossingthestreams.flutterappauth.FlutterAppauthPlugin, net.openid.appauth.AuthorizationServiceConfiguration, java.lang.String, java.lang.String, java.util.ArrayList, java.lang.String, java.util.Map, boolean) (FlutterAppauthPlugin.java:32)
I/net.auth.auth(14230):   at void io.crossingthestreams.flutterappauth.FlutterAppauthPlugin$1.onFetchConfigurationCompleted(net.openid.appauth.AuthorizationServiceConfiguration, net.openid.appauth.AuthorizationException) (FlutterAppauthPlugin.java:145)
I/net.auth.auth(14230):   at void net.openid.appauth.AuthorizationServiceConfiguration$ConfigurationRetrievalAsyncTask.onPostExecute(net.openid.appauth.AuthorizationServiceConfiguration) (AuthorizationServiceConfiguration.java:364)
I/net.auth.auth(14230):   at void net.openid.appauth.AuthorizationServiceConfiguration$ConfigurationRetrievalAsyncTask.onPostExecute(java.lang.Object) (AuthorizationServiceConfiguration.java:305)
I/net.auth.auth(14230):   at void android.os.AsyncTask.finish(java.lang.Object) (AsyncTask.java:695)
I/net.auth.auth(14230):   at void android.os.AsyncTask.access$600(android.os.AsyncTask, java.lang.Object) (AsyncTask.java:180)
I/net.auth.auth(14230):   at void android.os.AsyncTask$InternalHandler.handleMessage(android.os.Message) (AsyncTask.java:712)
I/net.auth.auth(14230):   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
I/net.auth.auth(14230):   at void android.os.Looper.loop() (Looper.java:193)
I/net.auth.auth(14230):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6669)
I/net.auth.auth(14230):   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/net.auth.auth(14230):   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:493)
I/net.auth.auth(14230):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:858)
I/net.auth.auth(14230): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.customtabs.CustomTabsServiceConnection" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/net.auth.auth-m_olvi3Sr5YUV6vbrYwsog==/base.apk"],nativeLibraryDirectories=[/data/app/net.auth.auth-m_olvi3Sr5YUV6vbrYwsog==/lib/x86, /data/app/net.auth.auth-m_olvi3Sr5YUV6vbrYwsog==/base.apk!/lib/x86, /system/lib]]
I/net.auth.auth(14230):   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:134)
I/net.auth.auth(14230):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
I/net.auth.auth(14230):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
I/net.auth.auth(14230):   at void net.openid.appauth.AuthorizationService.<init>(android.content.Context, net.openid.appauth.AppAuthConfiguration) (AuthorizationService.java:96)
I/net.auth.auth(14230):   at void net.openid.appauth.AuthorizationService.<init>(android.content.Context) (AuthorizationService.java:83)
I/net.auth.auth(14230):   at void io.crossingthestreams.flutterappauth.FlutterAppauthPlugin.performAuthorization(net.openid.appauth.AuthorizationServiceConfiguration, java.lang.String, java.lang.String, java.util.ArrayList, java.lang.String, java.util.Map, boolean) (FlutterAppauthPlugin.java:221)
I/net.auth.auth(14230):   at void io.crossingthestreams.flutterappauth.FlutterAppauthPlugin.access$200(io.crossingthestreams.flutterappauth.FlutterAppauthPlugin, net.openid.appauth.AuthorizationServiceConfiguration, java.lang.String, java.lang.String, java.util.ArrayList, java.lang.String, java.util.Map, boolean) (FlutterAppauthPlugin.java:32)
I/net.auth.auth(14230):   at void io.crossingthestreams.flutterappauth.FlutterAppauthPlugin$1.onFetchConfigurationCompleted(net.openid.appauth.AuthorizationServiceConfiguration, net.openid.appauth.AuthorizationException) (FlutterAppauthPlugin.java:145)
I/net.auth.auth(14230):   at void net.openid.appauth.AuthorizationServiceConfiguration$ConfigurationRetrievalAsyncTask.onPostExecute(net.openid.appauth.AuthorizationServiceConfiguration) (AuthorizationServiceConfiguration.java:364)
I/net.auth.auth(14230):   at void net.openid.appauth.AuthorizationServiceConfiguration$ConfigurationRetrievalAsyncTask.onPostExecute(java.lang.Object) (AuthorizationServiceConfiguration.java:305)
I/net.auth.auth(14230):   at void android.os.AsyncTask.finish(java.lang.Object) (AsyncTask.java:695)
I/net.auth.auth(14230):   at void android.os.AsyncTask.access$600(android.os.AsyncTask, java.lang.Object) (AsyncTask.java:180)
I/net.auth.auth(14230):   at void android.os.AsyncTask$InternalHandler.handleMessage(android.os.Message) (AsyncTask.java:712)
I/net.auth.auth(14230):   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
I/net.auth.auth(14230):   at void android.os.Looper.loop() (Looper.java:193)
I/net.auth.auth(14230):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6669)
I/net.auth.auth(14230):   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/net.auth.auth(14230):   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:493)
I/net.auth.auth(14230):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:858)
I/net.auth.auth(14230): 
I/net.auth.auth(14230): Rejecting re-init on previously-failed class java.lang.Class<net.openid.appauth.browser.CustomTabManager$1>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/customtabs/CustomTabsServiceConnection;
I/net.auth.auth(14230):   at void net.openid.appauth.AuthorizationService.<init>(android.content.Context, net.openid.appauth.AppAuthConfiguration) (AuthorizationService.java:96)
I/net.auth.auth(14230):   at void net.openid.appauth.AuthorizationService.<init>(android.content.Context) (AuthorizationService.java:83)
I/net.auth.auth(14230):   at void io.crossingthestreams.flutterappauth.FlutterAppauthPlugin.performAuthorization(net.openid.appauth.AuthorizationServiceConfiguration, java.lang.String, java.lang.String, java.util.ArrayList, java.lang.String, java.util.Map, boolean) (FlutterAppauthPlugin.java:221)
I/net.auth.auth(14230):   at void io.crossingthestreams.flutterappauth.FlutterAppauthPlugin.access$200(io.crossingthestreams.flutterappauth.FlutterAppauthPlugin, net.openid.appauth.AuthorizationServiceConfiguration, java.lang.String, java.lang.String, java.util.ArrayList, java.lang.String, java.util.Map, boolean) (FlutterAppauthPlugin.java:32)
I/net.auth.auth(14230):   at void io.crossingthestreams.flutterappauth.FlutterAppauthPlugin$1.onFetchConfigurationCompleted(net.openid.appauth.AuthorizationServiceConfiguration, net.openid.appauth.AuthorizationException) (FlutterAppauthPlugin.java:145)
I/net.auth.auth(14230):   at void net.openid.appauth.AuthorizationServiceConfiguration$ConfigurationRetrievalAsyncTask.onPostExecute(net.openid.appauth.AuthorizationServiceConfiguration) (AuthorizationServiceConfiguration.java:364)
I/net.auth.auth(14230):   at void net.openid.appauth.AuthorizationServiceConfiguration$ConfigurationRetrievalAsyncTask.onPostExecute(java.lang.Object) (AuthorizationServiceConfiguration.java:305)
I/net.auth.auth(14230):   at void android.os.AsyncTask.finish(java.lang.Object) (AsyncTask.java:695)
I/net.auth.auth(14230):   at void android.os.AsyncTask.access$600(android.os.AsyncTask, java.lang.Object) (AsyncTask.java:180)
I/net.auth.auth(14230):   at void android.os.AsyncTask$InternalHandler.handleMessage(android.os.Message) (AsyncTask.java:712)
I/net.auth.auth(14230):   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
I/net.auth.auth(14230):   at void android.os.Looper.loop() (Looper.java:193)
I/net.auth.auth(14230):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6669)
I/net.auth.auth(14230):   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/net.auth.auth(14230):   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:493)
I/net.auth.auth(14230):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:858)
I/net.auth.auth(14230): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.customtabs.CustomTabsServiceConnection" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/net.auth.auth-m_olvi3Sr5YUV6vbrYwsog==/base.apk"],nativeLibraryDirectories=[/data/app/net.auth.auth-m_olvi3Sr5YUV6vbrYwsog==/lib/x86, /data/app/net.auth.auth-m_olvi3Sr5YUV6vbrYwsog==/base.apk!/lib/x86, /system/lib]]
I/net.auth.auth(14230):   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:134)
I/net.auth.auth(14230):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
I/net.auth.auth(14230):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
I/net.auth.auth(14230):   at void net.openid.appauth.AuthorizationService.<init>(android.content.Context, net.openid.appauth.AppAuthConfiguration) (AuthorizationService.java:96)
I/net.auth.auth(14230):   at void net.openid.appauth.AuthorizationService.<init>(android.content.Context) (AuthorizationService.java:83)
I/net.auth.auth(14230):   at void io.crossingthestreams.flutterappauth.FlutterAppauthPlugin.performAuthorization(net.openid.appauth.AuthorizationServiceConfiguration, java.lang.String, java.lang.String, java.util.ArrayList, java.lang.String, java.util.Map, boolean) (FlutterAppauthPlugin.java:221)
I/net.auth.auth(14230):   at void io.crossingthestreams.flutterappauth.FlutterAppauthPlugin.access$200(io.crossingthestreams.flutterappauth.FlutterAppauthPlugin, net.openid.appauth.AuthorizationServiceConfiguration, java.lang.String, java.lang.String, java.util.ArrayList, java.lang.String, java.util.Map, boolean) (FlutterAppauthPlugin.java:32)
I/net.auth.auth(14230):   at void io.crossingthestreams.flutterappauth.FlutterAppauthPlugin$1.onFetchConfigurationCompleted(net.openid.appauth.AuthorizationServiceConfiguration, net.openid.appauth.AuthorizationException) (FlutterAppauthPlugin.java:145)
I/net.auth.auth(14230):   at void net.openid.appauth.AuthorizationServiceConfiguration$ConfigurationRetrievalAsyncTask.onPostExecute(net.openid.appauth.AuthorizationServiceConfiguration) (AuthorizationServiceConfiguration.java:364)
I/net.auth.auth(14230):   at void net.openid.appauth.AuthorizationServiceConfiguration$ConfigurationRetrievalAsyncTask.onPostExecute(java.lang.Object) (AuthorizationServiceConfiguration.java:305)
I/net.auth.auth(14230):   at void android.os.AsyncTask.finish(java.lang.Object) (AsyncTask.java:695)
I/net.auth.auth(14230):   at void android.os.AsyncTask.access$600(android.os.AsyncTask, java.lang.Object) (AsyncTask.java:180)
I/net.auth.auth(14230):   at void android.os.AsyncTask$InternalHandler.handleMessage(android.os.Message) (AsyncTask.java:712)
I/net.auth.auth(14230):   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
I/net.auth.auth(14230):   at void android.os.Looper.loop() (Looper.java:193)
I/net.auth.auth(14230):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6669)
I/net.auth.auth(14230):   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/net.auth.auth(14230):   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:493)
I/net.auth.auth(14230):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:858)
I/net.auth.auth(14230): 
I/net.auth.auth(14230): Rejecting re-init on previously-failed class java.lang.Class<net.openid.appauth.browser.CustomTabManager$1>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/customtabs/CustomTabsServiceConnection;
I/net.auth.auth(14230):   at void net.openid.appauth.AuthorizationService.<init>(android.content.Context, net.openid.appauth.AppAuthConfiguration) (AuthorizationService.java:96)
I/net.auth.auth(14230):   at void net.openid.appauth.AuthorizationService.<init>(android.content.Context) (AuthorizationService.java:83)
I/net.auth.auth(14230):   at void io.crossingthestreams.flutterappauth.FlutterAppauthPlugin.performAuthorization(net.openid.appauth.AuthorizationServiceConfiguration, java.lang.String, java.lang.String, java.util.ArrayList, java.lang.String, java.util.Map, boolean) (FlutterAppauthPlugin.java:221)
I/net.auth.auth(14230):   at void io.crossingthestreams.flutterappauth.FlutterAppauthPlugin.access$200(io.crossingthestreams.flutterappauth.FlutterAppauthPlugin, net.openid.appauth.AuthorizationServiceConfiguration, java.lang.String, java.lang.String, java.util.ArrayList, java.lang.String, java.util.Map, boolean) (FlutterAppauthPlugin.java:32)
I/net.auth.auth(14230):   at void io.crossingthestreams.flutterappauth.FlutterAppauthPlugin$1.onFetchConfigurationCompleted(net.openid.appauth.AuthorizationServiceConfiguration, net.openid.appauth.AuthorizationException) (FlutterAppauthPlugin.java:145)
I/net.auth.auth(14230):   at void net.openid.appauth.AuthorizationServiceConfiguration$ConfigurationRetrievalAsyncTask.onPostExecute(net.openid.appauth.AuthorizationServiceConfiguration) (AuthorizationServiceConfiguration.java:364)
I/net.auth.auth(14230):   at void net.openid.appauth.AuthorizationServiceConfiguration$ConfigurationRetrievalAsyncTask.onPostExecute(java.lang.Object) (AuthorizationServiceConfiguration.java:305)
I/net.auth.auth(14230):   at void android.os.AsyncTask.finish(java.lang.Object) (AsyncTask.java:695)
I/net.auth.auth(14230):   at void android.os.AsyncTask.access$600(android.os.AsyncTask, java.lang.Object) (AsyncTask.java:180)
I/net.auth.auth(14230):   at void android.os.AsyncTask$InternalHandler.handleMessage(android.os.Message) (AsyncTask.java:712)
I/net.auth.auth(14230):   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
I/net.auth.auth(14230):   at void android.os.Looper.loop() (Looper.java:193)
I/net.auth.auth(14230):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6669)
I/net.auth.auth(14230):   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/net.auth.auth(14230):   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:493)
I/net.auth.auth(14230):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:858)
I/net.auth.auth(14230): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.customtabs.CustomTabsServiceConnection" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/net.auth.auth-m_olvi3Sr5YUV6vbrYwsog==/base.apk"],nativeLibraryDirectories=[/data/app/net.auth.auth-m_olvi3Sr5YUV6vbrYwsog==/lib/x86, /data/app/net.auth.auth-m_olvi3Sr5YUV6vbrYwsog==/base.apk!/lib/x86, /system/lib]]
I/net.auth.auth(14230):   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:134)
I/net.auth.auth(14230):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
I/net.auth.auth(14230):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
I/net.auth.auth(14230):   at void net.openid.appauth.AuthorizationService.<init>(android.content.Context, net.openid.appauth.AppAuthConfiguration) (AuthorizationService.java:96)
I/net.auth.auth(14230):   at void net.openid.appauth.AuthorizationService.<init>(android.content.Context) (AuthorizationService.java:83)
I/net.auth.auth(14230):   at void io.crossingthestreams.flutterappauth.FlutterAppauthPlugin.performAuthorization(net.openid.appauth.AuthorizationServiceConfiguration, java.lang.String, java.lang.String, java.util.ArrayList, java.lang.String, java.util.Map, boolean) (FlutterAppauthPlugin.java:221)
I/net.auth.auth(14230):   at void io.crossingthestreams.flutterappauth.FlutterAppauthPlugin.access$200(io.crossingthestreams.flutterappauth.FlutterAppauthPlugin, net.openid.appauth.AuthorizationServiceConfiguration, java.lang.String, java.lang.String, java.util.ArrayList, java.lang.String, java.util.Map, boolean) (FlutterAppauthPlugin.java:32)
I/net.auth.auth(14230):   at void io.crossingthestreams.flutterappauth.FlutterAppauthPlugin$1.onFetchConfigurationCompleted(net.openid.appauth.AuthorizationServiceConfiguration, net.openid.appauth.AuthorizationException) (FlutterAppauthPlugin.java:145)
I/net.auth.auth(14230):   at void net.openid.appauth.AuthorizationServiceConfiguration$ConfigurationRetrievalAsyncTask.onPostExecute(net.openid.appauth.AuthorizationServiceConfiguration) (AuthorizationServiceConfiguration.java:364)
I/net.auth.auth(14230):   at void net.openid.appauth.AuthorizationServiceConfiguration$ConfigurationRetrievalAsyncTask.onPostExecute(java.lang.Object) (AuthorizationServiceConfiguration.java:305)
I/net.auth.auth(14230):   at void android.os.AsyncTask.finish(java.lang.Object) (AsyncTask.java:695)
I/net.auth.auth(14230):   at void android.os.AsyncTask.access$600(android.os.AsyncTask, java.lang.Object) (AsyncTask.java:180)
I/net.auth.auth(14230):   at void android.os.AsyncTask$InternalHandler.handleMessage(android.os.Message) (AsyncTask.java:712)
I/net.auth.auth(14230):   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
I/net.auth.auth(14230):   at void android.os.Looper.loop() (Looper.java:193)
I/net.auth.auth(14230):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6669)
I/net.auth.auth(14230):   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/net.auth.auth(14230):   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:493)
I/net.auth.auth(14230):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:858)
I/net.auth.auth(14230): 
D/AndroidRuntime(14230): Shutting down VM
E/AndroidRuntime(14230): FATAL EXCEPTION: main
E/AndroidRuntime(14230): Process: net.auth.auth, PID: 14230
E/AndroidRuntime(14230): java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/customtabs/CustomTabsServiceConnection;
E/AndroidRuntime(14230): 	at net.openid.appauth.AuthorizationService.<init>(AuthorizationService.java:96)
E/AndroidRuntime(14230): 	at net.openid.appauth.AuthorizationService.<init>(AuthorizationService.java:83)
E/AndroidRuntime(14230): 	at io.crossingthestreams.flutterappauth.FlutterAppauthPlugin.performAuthorization(FlutterAppauthPlugin.java:221)
E/AndroidRuntime(14230): 	at io.crossingthestreams.flutterappauth.FlutterAppauthPlugin.access$200(FlutterAppauthPlugin.java:32)
E/AndroidRuntime(14230): 	at io.crossingthestreams.flutterappauth.FlutterAppauthPlugin$1.onFetchConfigurationCompleted(FlutterAppauthPlugin.java:145)
E/AndroidRuntime(14230): 	at net.openid.appauth.AuthorizationServiceConfiguration$ConfigurationRetrievalAsyncTask.onPostExecute(AuthorizationServiceConfiguration.java:364)
E/AndroidRuntime(14230): 	at net.openid.appauth.AuthorizationServiceConfiguration$ConfigurationRetrievalAsyncTask.onPostExecute(AuthorizationServiceConfiguration.java:305)
E/AndroidRuntime(14230): 	at android.os.AsyncTask.finish(AsyncTask.java:695)
E/AndroidRuntime(14230): 	at android.os.AsyncTask.access$600(AsyncTask.java:180)
E/AndroidRuntime(14230): 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
E/AndroidRuntime(14230): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(14230): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(14230): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/AndroidRuntime(14230): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(14230): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(14230): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/AndroidRuntime(14230): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.customtabs.CustomTabsServiceConnection" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/net.auth.auth-m_olvi3Sr5YUV6vbrYwsog==/base.apk"],nativeLibraryDirectories=[/data/app/net.auth.auth-m_olvi3Sr5YUV6vbrYwsog==/lib/x86, /data/app/net.auth.auth-m_olvi3Sr5YUV6vbrYwsog==/base.apk!/lib/x86, /system/lib]]
E/AndroidRuntime(14230): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
E/AndroidRuntime(14230): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(14230): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(14230): 	... 16 more
I/Process (14230): Sending signal. PID: 14230 SIG: 9
Lost connection to device.
```

**Comment by MaikuB** [comment]
Just want to double check first but have you set the two flags mentioned in the guide in the grade.properties file? Also, does the demo app work run for you or do you run into the same problem? Suggest you clone the repo to check though as it has all of the platform-specific setup done already

**Comment by intako** [comment]
Added those flags you've mentioned above in _gradle.properties_:
```
android.enableJetifier=true
android.useAndroidX=true
```
I haven't  found it in the guide, probably I mislooked it.

Tried both your example and my app - it works as expected with custom openid connect identity provider's settings.
Appreciate your help, thanks!

**Comment by MaikuB** [comment]
No worries :)
