### ISSUE TITLE
Background execution error

### ISSUE THREAD

**Issue by GoltVik** [MaikuB/flutter_appauth#205]
Hello @MaikuB 
I'm getting this error with Crashlytics:

`Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void net.openid.appauth.g.f(net.openid.appauth.r, net.openid.appauth.g$b)' on a null object reference
       at io.crossingthestreams.flutterappauth.FlutterAppauthPlugin.performTokenRequest(FlutterAppauthPlugin.java:82)
       at io.crossingthestreams.flutterappauth.FlutterAppauthPlugin.access$500(FlutterAppauthPlugin.java)
       at io.crossingthestreams.flutterappauth.FlutterAppauthPlugin$3.onFetchConfigurationCompleted(FlutterAppauthPlugin.java:6)
       at net.openid.appauth.AuthorizationServiceConfiguration$ConfigurationRetrievalAsyncTask.onPostExecute(AuthorizationServiceConfiguration.java:13)
       at net.openid.appauth.AuthorizationServiceConfiguration$ConfigurationRetrievalAsyncTask.onPostExecute(AuthorizationServiceConfiguration.java:2)
       at android.os.AsyncTask.finish(AsyncTask.java:755)
       at android.os.AsyncTask.access$900(AsyncTask.java:192)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7860)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)` 

Can you fix that NullPointerException ?

**Comment by MaikuB** [comment]
The stack trace doesn't line up with any useful so you'd need to provide a minimal sample app with steps to reproduce the problem. There's one other similar report with a proposed fix (https://github.com/MaikuB/flutter_appauth/pull/170) but apparently they still had crashes.

**Comment by GoltVik** [comment]
Yes, sorry, this is a duplicate
