### ISSUE TITLE
flutter_appauth Android TagetSdkversion30 Not Redirect App. [Help Wanted]

### ISSUE THREAD

**Issue by steelhearts** [MaikuB/flutter_appauth#260]
It was Android targetSdkVersion 29 of the project under development.

To get it up on the Google Play Store, 

I set targetSdkVersion to 30 and configured AndroidManifest as follows.

https://pub.dev/packages/flutter_appauth
↑
Android setup 

```xml
<queries>
    <intent>
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data android:scheme="https" />
    </intent>
    <intent>
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.APP_BROWSER" />
        <data android:scheme="https" />
    </intent>
</queries>
```

It was working fine with targetSdkVersion 29.

I press the login button, and the redirection process seems to run, (WebView seems to be closed.)
but the app stays in the background and I can't get back into the app.

I investigated with Logcat, Debug, etc. to see if there were any exceptions, 
but I could not find any pertinent information.

Are there any other possible causes?

The version of the plugin I'm using is 0.9.2+6　

I am using this version plugin due to the fact that I cannot increase the version of Flutter.

**Comment by victorblaess** [comment]
Do you get something like this? I have the same problem as you but it works on API Level 29

```
PlatformException(authorize_and_exchange_code_failed, Failed to authorize: [error: null, description: Network error], null, null)
I/flutter ( 8422): PlatformException(authorize_and_exchange_code_failed, Failed to authorize: [error: null, description: Network error], null, null)
```

**Comment by steelhearts** [comment]
@victorblaess 
No, no such log was output.

It will be a simple one, but it is implemented as follows, and
PlatformException does not seem to be caught.

```dart
try {
      final response = await appAuth.authorizeAndExchangeCode(request);
      return _getKeycloakLoginResponseFromAuthorizationTokenResponse(response);
    } on PlatformException catch (err) {
   
      bool hasFailed = err.code == _loginFailedCode;
      bool hasCanceled = err.message.contains(RegExp(
          '$_androidLoginCancelMessage|$_iosLoginCancelMessage|$_iosSystemErrorMessage'));

      if (hasFailed && hasCanceled) {
        throw LoginException.hasCancel('login cancel, message=${err.message}');
      }

      throw LoginException.hasFailed(err.message);
    } catch (err) {
      rethrow;
    }
```

However, something strange is showing up in Logcat as a log, is this related?

```
2021-11-14 14:24:37.505 18767-18767/? I/AppCompatDelegate: Failed to instantiate custom view inflater com.google.android.material.theme.MaterialComponentsViewInflater. Falling back to default.
    java.lang.ClassNotFoundException: com.google.android.material.theme.MaterialComponentsViewInflater
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at java.lang.Class.forName(Class.java:379)
        at ie.onCreateView(chromium-TrichromeChromeGoogle.aab-stable-460608531:5)
        at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1061)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:997)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:659)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
        at com.android.internal.policy.DecorView.onResourcesLoaded(DecorView.java:2083)
        at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:2627)
        at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:2694)
        at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2094)
        at mX.k(chromium-TrichromeChromeGoogle.aab-stable-460608531:3)
        at org.chromium.base.ApplicationStatus.a(chromium-TrichromeChromeGoogle.aab-stable-460608531:19)
        at Yh.onActivityCreated(chromium-TrichromeChromeGoogle.aab-stable-460608531:1)
        at android.app.Application.dispatchActivityCreated(Application.java:373)
        at android.app.Activity.dispatchActivityCreated(Activity.java:1202)
        at android.app.Activity.onCreate(Activity.java:1475)
        at U70.onCreate(chromium-TrichromeChromeGoogle.aab-stable-460608531:6)
        at i01.onCreate(chromium-TrichromeChromeGoogle.aab-stable-460608531:1)
        at zU.onCreate(chromium-TrichromeChromeGoogle.aab-stable-460608531:7)
        at Gn.onCreate(chromium-TrichromeChromeGoogle.aab-stable-460608531:22)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.ClassNotFoundException: com.google.android.material.theme.MaterialComponentsViewInflater
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:454) 
        at java.lang.Class.forName(Class.java:379) 
        at ie.onCreateView(chromium-TrichromeChromeGoogle.aab-stable-460608531:5) 
        at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1061) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:997) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:659) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:481) 
        at com.android.internal.policy.DecorView.onResourcesLoaded(DecorView.java:2083) 
        at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:2627) 
        at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:2694) 
        at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2094) 
        at mX.k(chromium-TrichromeChromeGoogle.aab-stable-460608531:3) 
        at org.chromium.base.ApplicationStatus.a(chromium-TrichromeChromeGoogle.aab-stable-460608531:19) 
        at Yh.onActivityCreated(chromium-TrichromeChromeGoogle.aab-stable-460608531:1) 
        at android.app.Application.dispatchActivityCreated(Application.java:373) 
        at android.app.Activity.dispatchActivityCreated(Activity.java:1202) 
        at android.app.Activity.onCreate(Activity.java:1475) 
        at U70.onCreate(chromium-TrichromeChromeGoogle.aab-stable-460608531:6) 
        at i01.onCreate(chromium-TrichromeChromeGoogle.aab-stable-460608531:1) 
        at zU.onCreate(chromium-TrichromeChromeGoogle.aab-stable-460608531:7) 
        at Gn.onCreate(chromium-TrichromeChromeGoogle.aab-stable-460608531:22) 
        at android.app.Activity.performCreate(Activity.java:7802) 
        at android.app.Activity.performCreate(Activity.java:7791) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
2021-11-14 14:24:41.494 18767-18847/? E/cr_PackageMetrics: Could not parse UUID 111D-0C0A
    java.lang.IllegalArgumentException: Invalid UUID string: 111D-0C0A
        at java.util.UUID.fromString(UUID.java:194)
        at Fi2.a(chromium-TrichromeChromeGoogle.aab-stable-460608531:10)
        at IA2.c(chromium-TrichromeChromeGoogle.aab-stable-460608531:22)
        at Vn.call(chromium-TrichromeChromeGoogle.aab-stable-460608531:4)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at Wn.run(chromium-TrichromeChromeGoogle.aab-stable-460608531:5)
2021-11-14 14:24:43.828 2099-2116/? W/ActivityManager: Exception when unbinding service com.android.chrome/org.chromium.content.app.PrivilegedProcessService1
    android.os.DeadObjectException
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(BinderProxy.java:510)
        at android.app.IApplicationThread$Stub$Proxy.scheduleUnbindService(IApplicationThread.java:1612)
        at com.android.server.am.ActiveServices.removeConnectionLocked(ActiveServices.java:3146)
        at com.android.server.am.ActiveServices.killServicesLocked(ActiveServices.java:3547)
        at com.android.server.am.ActivityManagerService.cleanUpApplicationRecordLocked(ActivityManagerService.java:13694)
        at com.android.server.am.ActivityManagerService.handleAppDiedLocked(ActivityManagerService.java:3596)
        at com.android.server.am.ActivityManagerService.appDiedLocked(ActivityManagerService.java:3748)
        at com.android.server.am.ActivityManagerService$AppDeathRecipient.binderDied(ActivityManagerService.java:1504)
        at android.os.BinderProxy.sendDeathNotice(BinderProxy.java:620)

```

**Comment by MaikuB** [comment]
> The version of the plugin I'm using is 0.9.2+6　

@steelhearts therein lies your problem. That version uses an older version of the AppAuth Android SDK. Newer versions of this plugin would've used newer versions of the Android SDK that fixed compatibility issues with newer versions of Android. If you're going to stick with an old version of this plugin, then you'll need to using your own fork

> I am pretty sure, that this is the problem that we need to resolve somehow in flutter. @MaikuB
openid/AppAuth-Android#746

@victorblaess no it isn't. That issue you linked you has relation to this issue or the issue you've seen. Saying it's a Flutter issue doesn't make sense when the issue you've linked to is for the Android SDK and it doesn't use Flutter at all. The error message you've pasted even tells you what the problem is ("Network error"). This is something you'd need to look into as outside the control of this plugin and outside the control of the AppAuth Android SDK as well. If you were to create an Android app using Java or Kotlin and use the AppAuth Android SDK directly, you'd run into the same issue

**Comment by vicdotdevelop** [comment]
> > The version of the plugin I'm using is 0.9.2+6
> 
> @steelhearts therein lies your problem. That version uses an older version of the AppAuth Android SDK. Newer versions of this plugin would've used newer versions of the Android SDK that fixed compatibility issues with newer versions of Android. If you're going to stick with an old version of this plugin, then you'll need to using your own fork. There are docs on how you can use Git dependencies in your app at https://dart.dev/tools/pub/dependencies#git-packages
> 
> > I am pretty sure, that this is the problem that we need to resolve somehow in flutter. @MaikuB
> > [openid/AppAuth-Android#746](https://github.com/openid/AppAuth-Android/issues/746)
> 
> @victorblaess no it isn't. That issue you linked you has relation to this issue or the issue you've seen. Saying it's a Flutter issue doesn't make sense when the issue you've linked to is for the Android SDK and it doesn't use Flutter at all. The error message you've pasted even tells you what the problem is ("Network error"). This is something you'd need to look into as outside the control of this plugin and outside the control of the AppAuth Android SDK as well. If you were to create an Android app using Java or Kotlin and use the AppAuth Android SDK directly, you'd run into the same issue

You are right @MaikuB. New update of the package + newer gradle version did the trick.

**Comment by begandroide** [comment]
@MaikuB hi! im using this package and i has the same issue and console not show any error. Im using targetSdkVersion 30 too. 

Which is the gradle version that we need to use? because im using flutter_appauth in version 2.0.0.

**Comment by Juniorlpes** [comment]
> 

any solution?

**Comment by Juniorlpes** [comment]
> @MaikuB hi! im using this package and i has the same issue and console not show any error. Im using targetSdkVersion 30 too.
> 
> Which is the gradle version that we need to use? because im using flutter_appauth in version 2.0.0.

any solution?

**Comment by begandroide** [comment]
@Juniorlpes sorry I changed the package since I only needed Microsoft log-in. I used `flutter_microsoft_authentication`
