### ISSUE TITLE
iOS build fails with the dependecy

### ISSUE THREAD

**Issue by newDroidGuy** [MaikuB/flutter_appauth#270]
Hi,

The iOS build fails with the following error, on android the build works fine

CocoaPods' output:
↳
      Preparing
    Analyzing dependencies
    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)
    Finding Podfile changes
      A flutter_appauth
      - Flutter
      - connectivity_plus
      - flutter_secure_storage
      - path_provider
      - shared_preferences_ios
      - url_launcher
    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `connectivity_plus` from `.symlinks/plugins/connectivity_plus/ios`
    -> Fetching podspec for `flutter_appauth` from `.symlinks/plugins/flutter_appauth/ios`
    -> Fetching podspec for `flutter_secure_storage` from `.symlinks/plugins/flutter_secure_storage/ios`
    -> Fetching podspec for `path_provider` from `.symlinks/plugins/path_provider/ios`
    -> Fetching podspec for `shared_preferences_ios` from `.symlinks/plugins/shared_preferences_ios/ios`
    -> Fetching podspec for `url_launcher` from `.symlinks/plugins/url_launcher/ios`
    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_c_7_9.txt exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/c/7/9/Reachability/3.2/Reachability.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only performed in repo update
    ――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
    ### Command
    ```
    /usr/local/bin/pod install --verbose
    ```
    ### Report
    * What did you do?
    * What did you expect to happen?
    * What happened instead?
    ### Stack
    ```
       CocoaPods : 1.11.2
           Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
        RubyGems : 3.0.3
            Host : macOS 11.4 (20F71)
           Xcode : 12.5.1 (12E507)
             Git : git version 2.30.1 (Apple Git-130)
    Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
    Repositories : trunk - CDN - https://cdn.cocoapods.org/
```
    ### Plugins
    ```
    cocoapods-deintegrate : 1.0.5
    cocoapods-plugins     : 1.0.0
    cocoapods-search      : 1.0.1
    cocoapods-trunk       : 1.6.0
    cocoapods-try         : 1.2.0
    ```
    ### Podfile
    ```ruby
    # Uncomment this line to define a global platform for your project
    platform :ios, '11.0'
    # CocoaPods analytics sends network stats synchronously affecting flutter build latency.
    ENV['COCOAPODS_DISABLE_STATS'] = 'true'

    project 'Runner', {
      'Debug' => :debug,
      'Profile' => :release,
      'Release' => :release,
    }
    def flutter_root
      generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
      unless File.exist?(generated_xcode_build_settings_path)
        raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
      end
      File.foreach(generated_xcode_build_settings_path) do |line|
        matches = line.match(/FLUTTER_ROOT\=(.*)/)
        return matches[1].strip if matches
      end

      raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
    end
    require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)
    flutter_ios_podfile_setup
    target 'Runner' do
      flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
    end
    post_install do |installer|
      installer.pods_project.targets.each do |target|
        flutter_additional_ios_build_settings(target)
      end
    end
```
    ### Error
    ```
    LoadError - incompatible library version - /Users/xxxx/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/ffi-1.15.4/lib/ffi_c.bundle

2
    /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    /Users/xxxx/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/ffi-1.15.4/lib/ffi.rb:5:in `rescue in <top (required)>'
    /Users/xxxx/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/ffi-1.15.4/lib/ffi.rb:2:in `<top (required)>'
2
    /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    /Users/xxxx/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/ethon-0.14.0/lib/ethon.rb:3:in `<top (required)>'
2
    /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    /Users/xxxx/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'
2
    /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    /Users/xxxx/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/cdn_source.rb:440:in `download_typhoeus_impl_async'
    /Users/xxxx/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/cdn_source.rb:372:in `download_and_save_with_retries_async'
    /Users/xxxx/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/cdn_source.rb:365:in `download_file_async'
    /Users/xxxx/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/cdn_source.rb:338:in `download_file'
    /Users/xxxx/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/cdn_source.rb:284:in `ensure_versions_file_loaded'
    /Users/xxxx/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/cdn_source.rb:208:in `search'
    /Users/xxxx/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/source/aggregate.rb:83:in `block in search'
    /Users/xxxx/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/source/aggregate.rb:83:in `select'
    /Users/xxxx/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/source/aggregate.rb:83:in `search'
    /Users/xxxx/.rvm/gems/ruby-3.0.2/gems/cocoapods-1.11.2/lib/cocoapods/resolver.rb:416:in `create_set_from_sources'
 /Users/xxxx/.rvm/gems/ruby-3.0.2/gems/cocoapods-1.11.2/lib/cocoapods/resolver.rb:385:in `find_cached_set'
    /Users/xxxx/.rvm/gems/ruby-3.0.2/gems/cocoapods-1.11.2/lib/cocoapods/resolver.rb:360:in `specifications_for_dependency'
    /Users/xxxx/.rvm/gems/ruby-3.0.2/gems/cocoapods-1.11.2/lib/cocoapods/resolver.rb:165:in `search_for'
    /Users/xxxx/.rvm/gems/ruby-3.0.2/gems/cocoapods-1.11.2/lib/cocoapods/resolver.rb:274:in `block in sort_dependencies'
    /Users/xxxx/.rvm/gems/ruby-3.0.2/gems/cocoapods-1.11.2/lib/cocoapods/resolver.rb:267:in `each'
    /Users/xxxx/.rvm/gems/ruby-3.0.2/gems/cocoapods-1.11.2/lib/cocoapods/resolver.rb:267:in `sort_by'
    /Users/xxxx/.rvm/gems/ruby-3.0.2/gems/cocoapods-1.11.2/lib/cocoapods/resolver.rb:267:in `sort_by!'
    /Users/xxxx/.rvm/gems/ruby-3.0.2/gems/cocoapods-1.11.2/lib/cocoapods/resolver.rb:267:in `sort_dependencies'
    /Users/xxxx/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:60:in `block in sort_dependencies'
    /Users/xxxx/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:77:in `with_no_such_dependency_error_handling'
    /Users/xxxx/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:59:in `sort_dependencies'
/Users/xxxx/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:754:in `push_state_for_requirements'
    /Users/xxxx/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:744:in `require_nested_dependencies_for'
    /Users/xxxx/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:727:in `activate_new_spec'
    /Users/xxxx/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:684:in `attempt_to_activate'
    /Users/xxxx/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:254:in `process_topmost_state'
    /Users/xxxx/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:182:in `resolve'
    /Users/xxxx/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/molinillo-0.8.0/lib/molinillo/resolver.rb:43:in `resolve'
    /Users/xxxx/.rvm/gems/ruby-3.0.2/gems/cocoapods-1.11.2/lib/cocoapods/resolver.rb:94:in `resolve'
    /Users/xxxx/.rvm/gems/ruby-3.0.2/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:1078:in `block in resolve_dependencies'
    /Users/xxxx/.rvm/gems/ruby-3.0.2/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:64:in `section'
    /Users/xxxx/.rvm/gems/ruby-3.0.2/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:1076:in `resolve_dependencies'
    /Users/xxxx/.rvm/gems/ruby-3.0.2/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
    /Users/xxxx/.rvm/gems/ruby-3.0.2/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:416:in `analyze'
    /Users/xxxx/.rvm/gems/ruby-3.0.2/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:241:in `block in resolve_dependencies'
    /Users/xxxx/.rvm/gems/ruby-3.0.2/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:64:in `section'
    /Users/xxxx/.rvm/gems/ruby-3.0.2/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:240:in `resolve_dependencies'
    /Users/xxxx/.rvm/gems/ruby-3.0.2/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:161:in `install!'
    /Users/xxxx/.rvm/gems/ruby-3.0.2/gems/cocoapods-1.11.2/lib/cocoapods/command/install.rb:52:in `run'
    /Users/xxxx/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Users/xxxx/.rvm/gems/ruby-3.0.2/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in `run'
    /Users/xxxx/.rvm/gems/ruby-3.0.2/gems/cocoapods-1.11.2/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'
    ```
    ――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

    [!] Oh no, an error occurred.
    Search for existing GitHub issues similar to yours:
  
 https://github.com/CocoaPods/CocoaPods/search?q=incompatible+library+version+-+%2FUsers%2Fxxxx%2F.rvm%2Frubies%2Fruby-3.0.2%2Flib%2Fruby%2Fgems%2F3.0.0%2Fgems%2Fffi-1.15.4%2Flib%2Fffi_c.bundle&type=Issues

    If none exists, create a ticket, with the template displayed above, on:
    https://github.com/CocoaPods/CocoaPods/issues/new
    Be sure to first read the contributing guide for details on how to properly submit a ticket:
    https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md
    Don't forget to anonymize any private data!
    Looking for related issues on cocoapods/cocoapods...
    Found no similar issues. To create a new issue, please visit:
    https://github.com/cocoapods/cocoapods/issues/new
Error output from CocoaPods:
↳
    Ignoring executable-hooks-1.6.1 because its extensions are not built. Try: gem pristine executable-hooks --version 1.6.1
    Ignoring ffi-1.15.4 because its extensions are not built. Try: gem pristine ffi --version 1.15.4
    Ignoring gem-wrappers-1.4.0 because its extensions are not built. Try: gem pristine gem-wrappers --version 1.4.0
    Ignoring unf_ext-0.0.8 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8
    Ignoring unf_ext-0.0.7.7 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.7.7

Error running pod install
Error launching application on iPhone 11.

**Comment by MaikuB** [comment]
Nothing you posted there alludes to an issue with this plugin.  You'll need to take a closer look at the error and resolve whatever issue is there on your end. If it was to do with this plugin then there should be more reports on this. The example app would've failed to build as well yet you can see [here](https://github.com/MaikuB/flutter_appauth/runs/4297843711) that the last build was fine

**Comment by newDroidGuy** [comment]
Hi,
Thanks for replying. I have a weird problem, i'm able to run the example
project in M1 mac, but it fails in Intel Machine i have tried many ways
with solutions provided in online forums but no luck. Could you kindly help
me some way to solve this issue?  i got it verified in my friends
mac(intel) it works, but mine the pod install error always throws.

Regards,
Thejas
