### ISSUE TITLE
Find this issue on firebase crashlatics

### ISSUE THREAD

**Issue by bhanuka96** [MaikuB/flutter_appauth#326]
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void net.openid.appauth.j.a(net.openid.appauth.x, net.openid.appauth.j$b)' on a null object reference
       at io.crossingthestreams.flutterappauth.FlutterAppauthPlugin.a(FlutterAppauthPlugin.java:82)
       at io.crossingthestreams.flutterappauth.FlutterAppauthPlugin.access$1000(FlutterAppauthPlugin.java)
       at io.crossingthestreams.flutterappauth.FlutterAppauthPlugin$3.onFetchConfigurationCompleted(FlutterAppauthPlugin.java:6)
       at net.openid.appauth.AuthorizationServiceConfiguration$ConfigurationRetrievalAsyncTask.a(AuthorizationServiceConfiguration.java:13)
       at net.openid.appauth.AuthorizationServiceConfiguration$ConfigurationRetrievalAsyncTask.onPostExecute(AuthorizationServiceConfiguration.java:2)
       at android.os.AsyncTask.finish(AsyncTask.java:771)
       at android.os.AsyncTask.access$900(AsyncTask.java:199)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8653)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

code

```
    FlutterAppAuth appAuth = FlutterAppAuth();
    final String _issuer = '${tenantCatLogModel?.authorityUrl}';
    final AuthorizationServiceConfiguration _serviceConfiguration = AuthorizationServiceConfiguration(
        authorizationEndpoint: '${tenantCatLogModel?.authorityUrl}/connect/authorize', tokenEndpoint: '${tenantCatLogModel?.authorityUrl}/connect/token');
    return appAuth
        .authorizeAndExchangeCode(AuthorizationTokenRequest(_clientId, _redirectUrl,
            issuer: _issuer,
            scopes: _scopes,
            promptValues: ['login'],
            serviceConfiguration: _serviceConfiguration,
            preferEphemeralSession: Platform.isIOS))
```

**Comment by MaikuB** [comment]
Providing a crashlytics report doesn't help much. You'd need to provide a link to a minimal repo that can reproduce the problem and details on how to reproduce it
