### ISSUE TITLE
Crash On Android

### ISSUE THREAD

**Issue by ItzikAlkotzerAidoc** [MaikuB/flutter_appauth#355]
this is all I have

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Intent net.openid.appauth.AuthorizationService.getAuthorizationRequestIntent(net.openid.appauth.AuthorizationRequest)' on a null object reference
       at io.crossingthestreams.flutterappauth.FlutterAppauthPlugin.performAuthorization(FlutterAppauthPlugin.java:362)
       at io.crossingthestreams.flutterappauth.FlutterAppauthPlugin.access$400(FlutterAppauthPlugin.java:46)
       at io.crossingthestreams.flutterappauth.FlutterAppauthPlugin$2.onFetchConfigurationCompleted(FlutterAppauthPlugin.java:272)
       at net.openid.appauth.AuthorizationServiceConfiguration$ConfigurationRetrievalAsyncTask.onPostExecute(AuthorizationServiceConfiguration.java:417)
       at net.openid.appauth.AuthorizationServiceConfiguration$ConfigurationRetrievalAsyncTask.onPostExecute(AuthorizationServiceConfiguration.java:358)
       at android.os.AsyncTask.finish(AsyncTask.java:771)
       at android.os.AsyncTask.access$900(AsyncTask.java:199)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8653)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by ssorrychoi** [comment]
I have same this issue. Anybody resolve this issue?

**Comment by MaikuB** [comment]
Closing this due to lack of response from community. Note if you believe there's an issue with the plugin then please file a new issue with a link to a repository hosting a minimal app that can reproduce the issue and include steps on how to reproduce the problem too
