### ISSUE TITLE
ActivityNotFoundException on x86_64 architecture

### ISSUE THREAD

**Issue by lauroboeni** [MaikuB/flutter_appauth#357]
Recently I'm getting the following crash when submitting on the Google Play Store. The pre-launch report tests on an virtual Google Pixel 2 with Android 12 (SDK 31) and ABI x86_64

I'm using `flutter_appauth: ^2.4.2`

`FATAL EXCEPTION: main
Process: XXX.XXXXXX.XXX, PID: 9548
android.content.ActivityNotFoundException
	at net.openid.appauth.j.j(AuthorizationService.java:12)
	at net.openid.appauth.j.e(AuthorizationService.java:1)
	at net.openid.appauth.j.d(AuthorizationService.java:1)
	at j.a.a.b.w(FlutterAppauthPlugin.java:20)
	at j.a.a.b.d(FlutterAppauthPlugin.java:1)
	at j.a.a.b$a.a(FlutterAppauthPlugin.java:1)
	at net.openid.appauth.k$a.b(AuthorizationServiceConfiguration.java:3)
	at net.openid.appauth.k$a.onPostExecute(AuthorizationServiceConfiguration.java:1)
	at android.os.AsyncTask.finish(AsyncTask.java:771)
	at android.os.AsyncTask.access$900(AsyncTask.java:199)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)`

**Comment by MaikuB** [comment]
This might be one you'd need to look into further to see if there's a resolution or something else going on. I say this because the plugin ultimately makes use of other SDKs to do the work so errors like this are more likely to do with an issue with those SDKs
