### ISSUE TITLE
[iOS] throw exception when click "cancel" in the popup "... want to use ... to Sign in"

### ISSUE THREAD

**Issue by nguyenhuutinh** [MaikuB/flutter_appauth#55]
Hi,
anychance to not return exception if user click "cancel" 

```
flutter: #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
<asynchronous suspension>
#2      FlutterAppAuth.authorizeAndExchangeCode (package:flutter_appauth/src/flutter_appauth.dart:24:33)
```

**Comment by MaikuB** [comment]
No, as this is the standard behaviour of the SDKs that the plugin wraps around. It is up to your code to catch exceptions and handle appropriately. Catching it in at the plugin level makes it more difficult to diagnose actual issues

**Comment by nguyenhuutinh** [comment]
thanks
