### ISSUE TITLE
Missing Plugin Exception

### ISSUE THREAD

**Issue by kuttimania** [MaikuB/flutter_appauth#66]
Hi 
I am getting error like Missing Plugin Exception while implementing this  flutter_appauth Plugin

Exception has occurred.
MissingPluginException (MissingPluginException(No implementation found for method authorizeAndExchangeCode on channel crossingthestreams.io/flutter_appauth))

**Comment by MaikuB** [comment]
Can't say for sure without a link to a repo that can reproduce the problem but I'm guessing that perhaps you haven't made sure that Android side of your app is using AndroidX

**Comment by kuttimania** [comment]
> Can't say for sure without a link to a repo that can reproduce the problem but I'm guessing that perhaps you haven't made sure that Android side of your app is using AndroidX

Hi Maiku,
Its working in old package 0.5.0 but in new package 0.6.0 not working.

**Comment by MaikuB** [comment]
I don't think there should be change that would've caused the issue you're seeing unless it's Gradle related though I'm admittedly not an expert in that front. As per changelog, 0.6.0 now uses Gradle plugin 3.5.2. Worth seeing if your application use the same version will solve the problem. 

Otherwise, as stated above try cleaning your builds and/or provide a sample to reproduce the problem.

**Comment by ccbur** [comment]
Hi!

I have the same problem with 0.6.0. The old package 0.5.0 works as expected.

To reproduce you can take the example in the repository, change pubspec.yaml / dev_dependencies to 

`flutter_appauth: ^0.6.0
`

and after clicking on **Sign in with auto code exchange** you get

```
E/flutter (10396): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method authorizeAndExchangeCode on channel crossingthestreams.io/flutter_appauth)
E/flutter (10396): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:7)
E/flutter (10396): <asynchronous suspension>
E/flutter (10396): #1      FlutterAppAuth.authorizeAndExchangeCode (package:flutter_appauth/src/flutter_appauth.dart:24:57)
E/flutter (10396): <asynchronous suspension>
E/flutter (10396): #2      _MyAppState.build.<anonymous closure> (package:flutter_appauth_example/main.dart:123:47)
E/flutter (10396): <asynchronous suspension>
E/flutter (10396): #3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:654:14)
E/flutter (10396): #4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:729:32)
E/flutter (10396): #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (10396): #6      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
E/flutter (10396): #7      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:275:7)
E/flutter (10396): #8      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:455:9)
E/flutter (10396): #9      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:75:13)
E/flutter (10396): #10     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:102:11)
E/flutter (10396): #11     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter (10396): #12     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (10396): #13     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (10396): #14     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (10396): #15     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (10396): #16     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter (10396): #17     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (10396): #18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter (10396): #19     _invoke1 (dart:ui/hooks.dart:263:10)
E/flutter (10396): #20     _dispatchPointerDataPacket (dart:ui/hooks.dart:172:5)
```

**Comment by MaikuB** [comment]
Did that but don't run into the issue. Mind include the output of `flutter doctor -v`?

**Comment by ccbur** [comment]
Here my `flutter doctor -v`:

```
[√] Flutter (Channel stable, v1.9.1+hotfix.5, on Microsoft Windows [Version 10.0.17134.1246], locale de-DE)
    • Flutter version 1.9.1+hotfix.5 at c:\tools\flutter
    • Framework revision 1aedbb1835 (3 months ago), 2019-10-17 08:37:27 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Android\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Android\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8580
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code, 64-bit edition (version 1.31.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.25.1

[√] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is localhost,127.0.0.1
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains localhost

[√] Connected device (1 available)
    • ONEPLUS A3003 • cb9cf1fa • android-arm64 • Android 9 (API 28)

• No issues found!

```

**Comment by MaikuB** [comment]
Can you try updating Android studio to 3.5.3?

**Comment by ccbur** [comment]
I will, but it'll need some days.

**Comment by MaikuB** [comment]
If that fails, another thing to try is updating your version of the Flutter SDK to the latest stable (1.12) though I don't recall there being changes in 0.60 that would require developers to do so.

**Comment by ccbur** [comment]
Without updating Android studio I updated flutter to 1.12.13+hotfix.7 and it works now with the current package 0.6.0.

Here my `flutter doctor -v`:

```
[√] Flutter (Channel stable, v1.12.13+hotfix.7, on Microsoft Windows [Version 10.0.17134.1246], locale de-DE)
    • Flutter version 1.12.13+hotfix.7 at c:\tools\flutter
    • Framework revision 9f5ff2306b (2 days ago), 2020-01-26 22:38:26 -0800
    • Engine revision a67792536c
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Android\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Android\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code, 64-bit edition (version 1.31.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.25.1

[√] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is localhost,127.0.0.1
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains localhost

[√] Connected device (1 available)
    • ONEPLUS A3003 • cb9cf1fa • android-arm64 • Android 9 (API 28)

• No issues found!

```

So I'm fine now. :-)

**Comment by MaikuB** [comment]
Great to hear. I'll try rolling back to see if I get the same issue. If so, I'll need bump the min version in the pubspec and retroactively update the changelog for 0.6.0

**Comment by MaikuB** [comment]
Ok I can reproduce the issue. Perhaps the change to the new pubspec format was specific to Flutter 1.12. Apologies for the inconvenience

**Comment by ccbur** [comment]
No problem at all. Thanks for your great work!
